# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 02:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('patientid', models.AutoField(primary_key=True, serialize=False)),
                ('adress', models.TextField()),
                ('telephone', models.FloatField()),
                ('mobile', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
