# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('patientid', models.FloatField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('phoneno', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
